behaviors:
  SoloPusher:
    trainer_type: ppo
    hyperparameters:
      batch_size: 500
      buffer_size: 10000
      learning_rate: 5.0e-3
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      # extrinsic:
      #   gamma: 0.99
      #   strength: 1.0
      gail:  # Используем GAIL (имитационное обучение)
        strength: 1.0  # Влияние демонстраций на обучение
        gamma: 0.99
        demo_path: Assets/Demos/Amogus.demo
      # curiosity:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 128
      #   learning_rate: 5.0e-3
    checkpoint_interval: 10000
    keep_checkpoints: 200
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 10000
