behaviors:
  SoloPusher:
    trainer_type: ppo
    hyperparameters:
      batch_size: 200
      buffer_size: 2000
      learning_rate: 1.0e-4
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
      # curiosity:
      #   strength: 0.01
      #   gamma: 0.99
      #   encoding_size: 256
      #   learning_rate: 1.0e-4
      #   network_settings:
      #     normalize: true
      #     hidden_units: 256
      #     num_layers: 2
      #     vis_encode_type: simple
    checkpoint_interval: 50000
    keep_checkpoints: 200
    max_steps: 6000000
    time_horizon: 1000
    summary_freq: 10000
